#!/usr/bin/env bash
# ---------------------------------------------------------------------------
#  Download what ImageWorker needs to build on Linux or macOS.
#
#  Qt and OpenCV come from the system package manager — they are large, and a
#  distribution build is the one the rest of the system already agrees with.
#  This script fetches the pieces that have no package: ONNX Runtime and the
#  model weights. It prints the one command to install the rest.
#
#    tools/fetch-deps.sh              fetch everything missing
#    tools/fetch-deps.sh --force      re-download even if present
#    tools/fetch-deps.sh --no-models  skip the ~70 MB of weights
# ---------------------------------------------------------------------------
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS="$HOME/imageworker-deps"
MODELS="$ROOT/models"

ORT_VERSION=1.24.1
MODEL_RELEASE=v1.0.0

FORCE=0
WANT_MODELS=1
for arg in "$@"; do
    case "$arg" in
        --force)     FORCE=1 ;;
        --no-models) WANT_MODELS=0 ;;
        *) echo "unknown option: $arg"; exit 2 ;;
    esac
done

mkdir -p "$DEPS" "$MODELS"

case "$(uname -s)" in
    Linux)  PLATFORM=linux ;;
    Darwin) PLATFORM=macos ;;
    *) echo "unsupported platform: $(uname -s)"; exit 1 ;;
esac

# --- system packages ---------------------------------------------------------
missing=()
command -v cmake >/dev/null || missing+=(cmake)
command -v ninja >/dev/null || missing+=(ninja)

if [ "$PLATFORM" = linux ]; then
    command -v qmake6 >/dev/null 2>&1 || pkg-config --exists Qt6Core 2>/dev/null || missing+=(qt6-base-dev)
    pkg-config --exists opencv4 2>/dev/null || missing+=(libopencv-dev)
    if [ ${#missing[@]} -gt 0 ]; then
        echo "Missing system packages: ${missing[*]}"
        echo "  sudo apt install -y qt6-base-dev libqt6sql6-sqlite libopencv-dev cmake ninja-build"
        echo
    fi
else
    brew list --versions qt     >/dev/null 2>&1 || missing+=(qt)
    brew list --versions opencv >/dev/null 2>&1 || missing+=(opencv)
    if [ ${#missing[@]} -gt 0 ]; then
        echo "Missing Homebrew packages: ${missing[*]}"
        echo "  brew install cmake ninja qt opencv"
        echo
    fi
fi

# --- ONNX Runtime ------------------------------------------------------------
# Linux gets the GPU package: it carries the CUDA provider as well as the CPU
# one, and falls back cleanly on a machine without a card. macOS arm64 ships
# CoreML in the standard package.
if [ "$PLATFORM" = linux ]; then
    if command -v nvidia-smi >/dev/null 2>&1; then
        ORT_NAME="onnxruntime-linux-x64-gpu-$ORT_VERSION"
    else
        ORT_NAME="onnxruntime-linux-x64-$ORT_VERSION"
    fi
elif [ "$(uname -m)" = arm64 ]; then
    ORT_NAME="onnxruntime-osx-arm64-$ORT_VERSION"
else
    ORT_NAME="onnxruntime-osx-x86_64-$ORT_VERSION"
fi

if [ -d "$DEPS/$ORT_NAME" ] && [ $FORCE -eq 0 ]; then
    echo "ONNX Runtime: already at $DEPS/$ORT_NAME"
else
    echo "ONNX Runtime: fetching $ORT_NAME"
    curl -fsSL -o "$DEPS/ort.tgz" \
        "https://github.com/microsoft/onnxruntime/releases/download/v$ORT_VERSION/$ORT_NAME.tgz" || {
            echo "  download failed"; exit 1; }
    tar -xzf "$DEPS/ort.tgz" -C "$DEPS"
    rm -f "$DEPS/ort.tgz"
    echo "  -> $DEPS/$ORT_NAME"
fi

# --- CUDA runtime and cuDNN, for the Linux GPU build -------------------------
# Wheels rather than the CUDA toolkit: they contain exactly the shared libraries
# the provider dlopens, need no root, and cannot disturb the display driver.
# cuDNN is pinned — 9.24 creates the session and then fails at the first
# convolution with CUDNN_BACKEND_API_FAILED. 9.8 is the newest that runs.
if [ "$PLATFORM" = linux ] && command -v nvidia-smi >/dev/null 2>&1; then
    NVDIR="$DEPS/nvidia"
    if [ -d "$NVDIR" ] && [ $FORCE -eq 0 ]; then
        echo "CUDA runtime + cuDNN: already unpacked"
    else
        echo "CUDA runtime + cuDNN 9.8:"
        WHEELS="$DEPS/wheels"
        mkdir -p "$WHEELS" "$NVDIR"
        python3 -m pip download --quiet --dest "$WHEELS" --only-binary=:all: \
            nvidia-cuda-runtime-cu12 nvidia-cuda-nvrtc-cu12 nvidia-cublas-cu12 \
            nvidia-cufft-cu12 nvidia-curand-cu12 "nvidia-cudnn-cu12==9.8.0.87" \
            || { echo "  pip download failed"; exit 1; }
        for w in "$WHEELS"/*.whl; do python3 -m zipfile -e "$w" "$NVDIR"; done
        echo "  -> $NVDIR"
    fi
fi

# --- runtime environment -----------------------------------------------------
{
    echo "# Generated by tools/fetch-deps.sh — source before running the binaries."
    LIBS="$DEPS/$ORT_NAME/lib"
    if [ -d "$DEPS/nvidia" ]; then
        NVLIBS=$(find "$DEPS/nvidia" -name lib -type d | tr '\n' ':')
        LIBS="${NVLIBS}${LIBS}"
    fi
    if [ "$PLATFORM" = macos ]; then
        echo "export DYLD_LIBRARY_PATH=\"$LIBS:\${DYLD_LIBRARY_PATH:-}\""
    else
        echo "export LD_LIBRARY_PATH=\"$LIBS:\${LD_LIBRARY_PATH:-}\""
    fi
} > "$DEPS/env.sh"
echo "environment: $DEPS/env.sh"

# --- model weights -----------------------------------------------------------
if [ $WANT_MODELS -eq 0 ]; then
    echo "Models: skipped"
else
    echo "Models:"
    # Release v1.0.0 on purpose: later ones ship a fused extractor+matcher, which
    # would force re-extracting every asset on every query.
    for m in disk.onnx disk_lightglue_fused_fp16.onnx disk_lightglue_fused_cpu.onnx; do
        if [ -f "$MODELS/$m" ] && [ $FORCE -eq 0 ]; then
            echo "  cached  $m"
        else
            echo "  fetch   $m"
            curl -fsSL -o "$MODELS/$m" \
                "https://github.com/fabio-sim/LightGlue-ONNX/releases/download/$MODEL_RELEASE/$m" \
                || { echo "  download failed"; exit 1; }
        fi
    done
    echo "  -> $MODELS"
fi

echo
echo "Done. Build with: tools/build.sh"
